### ISSUE TITLE
Implement lexical closeness measurement

### ISSUE THREAD

**Issue by anaothmane** [anaothmane/spect#1]
# Problem

Word embeddings are just vectors, so assessing how close they are to each other is a simple cosine similarity measurement (either through `sklearn.metrics.pairwise` or `numpy.spatial.distance`). But here we're interested in knowing how close a `target` is from a `word bank`, so the following complications arise:

1. Several words are present in a word bank;
2. Some words may be negatively correlated with the perspective while others may not (e.g. "creativity" dimension with "imaginative" vs. "dull".

# Subtasks

- [ ] Re-implement the closeness measures presented in the [Caliskan-Islam paper](http://www.princeton.edu/~aylinc/papers/caliskan-islam_semantics.pdf). Work to be done in notebook, and using pre-existing word embeddings.
- [ ] Specify tests in notebook
- [ ] Write tests in code
- [ ] Implement code

# Issues not considered
- Double counting of words across subdimensions
