### ISSUE TITLE
Perspective measurements across multiple dimensions

### ISSUE THREAD

**Issue by anaothmane** [anaothmane/spect#2]
Once #1 is implemented, the resulting code needs to be used across several dimensions to get a personality spiderweb for public personas.

# Subtasks
- [ ] Create a multidimensional version of closeness measurements
- [ ] Write a notebook that goes from word vectors + target to visualisation
- [ ] Write tests for helper code
- [ ] Write helper codes to directly go from text+target to perspective measurement
- [ ] Put the visualisation of the personality dimensions in the spect code

# Issues not considered
- Time variation in visualisation. This just outputs an image for static inputs.
